name: actions

on:
  workflow_dispatch:  # 允许通过网页手动触发
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # windows-latest is disabled due to cmake failure:
        # https://github.com/awvwgk/setup-fortran/issues/6
        os: [ubuntu-latest, macOS-latest]
        gcc_version: [13]
        compiler: ['make', 'cmake']

    steps:
    - uses: actions/checkout@v4
    - uses: fortran-lang/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: ${{ matrix.gcc_version }}

    - name: Compile using make
      if: matrix.compiler == 'make'
      run: |
        ./configure
        make
      shell: bash

    - name: Compile using cmake
      if: matrix.compiler == 'cmake'
      run: |
        cmake ./ && cmake --build ./
      shell: bash

    - name: Run
      run: |
          cd testing
          ./install_julia.sh
          ./test.sh
      shell: bash

  compile-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fortran-lang/setup-fortran@main
        with:
          compiler: gfortran
      - name: Compile using Make
        run: |
          ./configure
          make
        shell: bash
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: packmol-exe
          path: packmol.exe
